export interface CreditTier {
  credits: number;
  label: string;
  additionalPrice: number;
}

export interface PlanTier {
  id: string;
  name: string;
  description: string;
  monthlyPrice: number | null;
  annualFirstMonthPrice: number | null; // 50% off first month
  badge?: string;
  highlight: boolean;
  cta: string;
  ctaVariant: 'primary' | 'outline';
  ctaAction: 'auth' | 'checkout' | 'contact';
  featuresIntro?: string;
  features: string[];
  hasCreditSelector: boolean;
  hasAnnualToggle: boolean;
}

export const CREDIT_TIERS: CreditTier[] = [
  { credits: 100, label: '100 credits per month', additionalPrice: 0 },
  { credits: 200, label: '200 credits per month', additionalPrice: 15 },
  { credits: 500, label: '500 credits per month', additionalPrice: 40 },
];

export const PLANS: PlanTier[] = [
  {
    id: 'pro',
    name: 'Pro',
    description: 'Built for fast-moving teams shipping in real time.',
    monthlyPrice: 25,
    annualFirstMonthPrice: 12.5,
    highlight: true,
    cta: 'Upgrade',
    ctaVariant: 'primary',
    ctaAction: 'checkout',
    hasCreditSelector: true,
    hasAnnualToggle: true,
    featuresIntro: 'All Free features, plus:',
    features: [
      '100 monthly credits',
      '5 daily credits (up to 150/month)',
      'Usage-based Cloud + AI',
      'Credit rollovers',
      'On-demand credit top-ups',
      'Unlimited blink.app domains',
      'Custom domains',
      'Remove the Blink badge',
      'User roles & permissions',
    ],
  },
  {
    id: 'business',
    name: 'Business',
    description: 'Advanced controls and power features for growing departments.',
    monthlyPrice: 50,
    annualFirstMonthPrice: 25,
    highlight: false,
    cta: 'Upgrade',
    ctaVariant: 'outline',
    ctaAction: 'checkout',
    hasCreditSelector: true,
    hasAnnualToggle: true,
    featuresIntro: 'All Pro features, plus:',
    features: [
      '100 monthly credits',
      'Internal publish',
      'SSO',
      'Team workspace',
      'Personal projects',
      'Design templates',
      'Role-based access',
      'Security center',
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    description: 'Built for large organizations needing flexibility, scalability and governance.',
    monthlyPrice: null,
    annualFirstMonthPrice: null,
    highlight: false,
    cta: 'Book a Demo',
    ctaVariant: 'outline',
    ctaAction: 'contact',
    hasCreditSelector: false,
    hasAnnualToggle: false,
    featuresIntro: 'All Business features, plus:',
    features: [
      'Dedicated support',
      'Onboarding services',
      'Design systems',
      'SCIM',
      'Support for custom connectors',
      'Publishing controls',
      'Sharing controls',
      'Audit logs (coming soon!)',
    ],
  },
];

export const FAQ_ITEMS = [
  {
    question: 'What is Blink and how does it work?',
    answer: 'Blink is an AI-powered app builder that turns your ideas into real, full-stack web applications. Just describe what you want to build in plain English, and Blink generates production-ready code, deploys it, and gives you a live URL — all in seconds.',
  },
  {
    question: 'What does the free plan include?',
    answer: 'The free plan includes 5 daily credits (up to 30 per month), public projects, unlimited collaborators, 5 blink.app domains, and access to Blink Cloud. It\'s perfect for trying out the platform and building prototypes.',
  },
  {
    question: 'What is a credit?',
    answer: 'A credit corresponds to one interaction with the AI — a generation request, an iteration, or a code modification. Credits reset each month on paid plans, and daily credits refresh every day.',
  },
  {
    question: 'What technologies does Blink support?',
    answer: 'Blink generates production-ready React applications with TypeScript, Tailwind CSS, and Vite. It also supports backend features through Blink Cloud including databases, authentication, edge functions, and file storage.',
  },
  {
    question: 'Who owns the projects and code?',
    answer: 'You do. All code generated by Blink is 100% yours. You can export it as a ZIP file (Pro plan and above), host it anywhere, and modify it freely. We don\'t claim any ownership over your projects.',
  },
  {
    question: 'How much does it cost to use?',
    answer: 'Blink offers a generous free tier to get started. The Pro plan starts at $12.50/month for the first month (then $25/month), and includes 100 monthly credits with the option to add more. The Business plan starts at $25/month for the first month (then $50/month) for teams. Enterprise pricing is custom.',
  },
  {
    question: 'How does Cloud + AI pricing work?',
    answer: 'Cloud + AI usage is billed based on actual consumption. This includes database operations, edge function invocations, file storage, and AI model calls. Each plan includes a free tier of Cloud + AI usage, with additional usage billed at competitive rates.',
  },
  {
    question: 'Do you offer a student discount?',
    answer: 'Yes! Students get up to 50% off the Pro plan. Verify your student status to claim your discount.',
  },
  {
    question: 'Where can I find more information?',
    answer: 'Visit our documentation at docs.blink.ai for comprehensive guides, tutorials, and API references. You can also join our community on Discord for real-time support and discussions.',
  },
];
