export interface CreditTier {
  credits: number;
  label: string;
  additionalPrice: number; // added to base price
}

export interface PlanTier {
  id: string;
  name: string;
  description: string;
  monthlyPrice: number | null;
  yearlyMonthlyPrice: number | null; // price per month when billed yearly
  badge?: string;
  highlight: boolean;
  cta: string;
  ctaAction: 'auth' | 'checkout' | 'contact';
  featuresIntro?: string;
  features: string[];
  hasCreditSelector: boolean;
  hasAnnualToggle: boolean;
}

export const CREDIT_TIERS: CreditTier[] = [
  { credits: 100, label: '100 credits / month', additionalPrice: 0 },
  { credits: 200, label: '200 credits / month', additionalPrice: 15 },
  { credits: 500, label: '500 credits / month', additionalPrice: 40 },
];

export const PLANS: PlanTier[] = [
  {
    id: 'free',
    name: 'Free',
    description: 'For hobbyists and casual exploration.',
    monthlyPrice: 0,
    yearlyMonthlyPrice: 0,
    highlight: false,
    cta: 'Get Started',
    ctaAction: 'auth',
    hasCreditSelector: false,
    hasAnnualToggle: false,
    features: [
      '5 daily credits (up to 30/month)',
      'Public projects',
      'Unlimited collaborators',
      '5 blink.app domains',
      'Cloud',
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    description: 'For creators who need more power.',
    monthlyPrice: 25,
    yearlyMonthlyPrice: 20,
    badge: 'Popular',
    highlight: true,
    cta: 'Get Started',
    ctaAction: 'checkout',
    hasCreditSelector: true,
    hasAnnualToggle: true,
    featuresIntro: 'Everything in Free, plus:',
    features: [
      '100 monthly credits',
      '5 daily credits (up to 150/month)',
      'Usage-based Cloud + AI',
      'Credit rollovers',
      'On-demand credit top-ups',
      'Unlimited blink.app domains',
      'Custom domains',
      'Remove the Blink badge',
      'User roles & permissions',
    ],
  },
  {
    id: 'business',
    name: 'Business',
    description: 'For teams building together.',
    monthlyPrice: 50,
    yearlyMonthlyPrice: 40,
    highlight: false,
    cta: 'Get Started',
    ctaAction: 'checkout',
    hasCreditSelector: true,
    hasAnnualToggle: true,
    featuresIntro: 'Everything in Pro, plus:',
    features: [
      '100 monthly credits',
      'Internal publish',
      'SSO',
      'Team workspace',
      'Personal projects',
      'Design templates',
      'Role-based access',
      'Security center',
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    description: 'Custom solutions for organizations.',
    monthlyPrice: null,
    yearlyMonthlyPrice: null,
    highlight: false,
    cta: 'Book a Demo',
    ctaAction: 'contact',
    hasCreditSelector: false,
    hasAnnualToggle: false,
    featuresIntro: 'Everything in Business, plus:',
    features: [
      'Dedicated support',
      'Onboarding services',
      'Design systems',
      'SCIM provisioning',
      'Support for custom connectors',
      'Publishing controls',
      'Sharing controls',
      'Audit logs (coming soon!)',
    ],
  },
];

export const FAQ_ITEMS = [
  {
    question: 'What is Blink and how does it work?',
    answer: 'Blink is an AI-powered app builder that turns your ideas into real, full-stack web applications. Just describe what you want to build in plain English, and Blink generates production-ready code, deploys it, and gives you a live URL — all in seconds.',
  },
  {
    question: 'What does the free plan include?',
    answer: 'The free plan includes 5 daily credits (up to 30 per month), public projects, unlimited collaborators, 5 blink.app domains, and access to Blink Cloud. It\'s perfect for trying out the platform and building prototypes.',
  },
  {
    question: 'What is a credit?',
    answer: 'A credit corresponds to one interaction with the AI — a generation request, an iteration, or a code modification. Credits reset each month on paid plans, and daily credits refresh every day.',
  },
  {
    question: 'Who owns the projects and code?',
    answer: 'You do. All code generated by Blink is 100% yours. You can export it as a ZIP file (Pro plan and above), host it anywhere, and modify it freely. We don\'t claim any ownership over your projects.',
  },
  {
    question: 'How much does it cost to use?',
    answer: 'Blink offers a generous free tier to get started. The Pro plan starts at $20/month (billed annually) or $25/month, and includes 100 monthly credits with the option to add more. The Business plan starts at $40/month (billed annually) for teams. Enterprise pricing is custom.',
  },
  {
    question: 'Do you offer a student discount?',
    answer: 'Yes! Students get 50% off the Pro plan. Contact us with your student email address to claim your discount.',
  },
];
